### ISSUE TITLE
"Build the Docker Image" section in README

### ISSUE THREAD

**Issue by jimsheldon** [harness-community/drone-get-maven-version#4]
Should this section be removed? https://github.com/harness-community/drone-maven-docker-image-builder/blob/main/README.md?plain=1#L11-L17

There is no `build_and_push_docker_image.sh` file in the repository.

**Comment by Ompragash** [comment]
Initially, this plugin was built in a way to get the maven version and then builds & pushed the image to docker registry. Now, it follows the same pattern as https://github.com/marketplace/actions/get-current-pom-version shared on the ticket CI-9469.

**Comment by justAkshitAgrawal** [comment]
Fixing this

**Comment by justAkshitAgrawal** [comment]
Fix: https://github.com/harness-community/drone-maven-docker-image-builder/pull/3
